services:
  custom-basket-ui:
    image: ghcr.io/bonnemai/custom_basket_ui:latest
    # image: ghcr.io/bonnemai/custom_basket_ui:latest@sha256:aebe5770d2e82c86145b5ac40ddbbe0947d1a88281a707113c2b8bdd7ca464b5
    platform: linux/amd64
    ports:
      - "8080:80"
    restart: unless-stopped
  custom-basket-api:
    image: ghcr.io/bonnemai/custom-basket:latest
    platform: linux/amd64
    ports:
      - "8000:8000"
    restart: unless-stopped
