apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-basket-ui
  labels:
    app: custom-basket-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-basket-ui
  template:
    metadata:
      labels:
        app: custom-basket-ui
    spec:
      containers:
        - name: custom-basket-ui
          image: custom-basket-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: VITE_CUSTOM_BASKET_API_URL
              value: https://custom-basket-api.20urgjtsc9b0.eu-gb.codeengine.appdomain.cloud/
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
