apiVersion: v1
kind: Service
metadata:
  name: custom-basket-ui
  labels:
    app: custom-basket-ui
spec:
  selector:
    app: custom-basket-ui
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
