name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure pricing API urls
        run: |
          if [ -n "${{ secrets.VITE_PRICING_API_URL }}" ]; then
            echo "VITE_PRICING_API_URL=${{ secrets.VITE_PRICING_API_URL }}" >> $GITHUB_ENV
          else
            echo "VITE_PRICING_API_URL=http://localhost:8000/pricing/basket" >> $GITHUB_ENV
          fi

          if [ -n "${{ secrets.VITE_PRICING_API_DOCS_URL }}" ]; then
            echo "VITE_PRICING_API_DOCS_URL=${{ secrets.VITE_PRICING_API_DOCS_URL }}" >> $GITHUB_ENV
          else
            echo "VITE_PRICING_API_DOCS_URL=http://localhost:8000/docs" >> $GITHUB_ENV
          fi

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          build-args: |
            VITE_PRICING_API_URL=${{ env.VITE_PRICING_API_URL }}
            VITE_PRICING_API_DOCS_URL=${{ env.VITE_PRICING_API_DOCS_URL }}
