name: Build and Deploy UI

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

env:
  VITE_CUSTOM_BASKET_API_URL: https://6adnqiwsenkvr2lasnrw25h5hm0ghlfb.lambda-url.eu-west-2.on.aws
  S3_BUCKET: custom-basket-ui
  BUILD_DIR: dist
  AWS_REGION: eu-west-2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prd
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: npm

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          VITE_CUSTOM_BASKET_API_URL: ${{ env.VITE_CUSTOM_BASKET_API_URL }}

      - name: Upload dist artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: dist
          path: ${{ env.BUILD_DIR }}

      - name: Configure AWS credentials
        if: github.event_name != 'pull_request'
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync dist to S3
        if: github.event_name != 'pull_request'
        run: aws s3 sync ${{ env.BUILD_DIR }} s3://${{ env.S3_BUCKET }} --delete
