name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure basket API url
        run: |
          BASE_URL="${{ secrets.VITE_CUSTOM_BASKET_API_URL }}"
          if [ -z "$BASE_URL" ]; then
            BASE_URL="http://localhost:8000/"
          fi
          case "$BASE_URL" in
            */) : ;;
            *) BASE_URL="$BASE_URL/" ;;
          esac
          echo "VITE_CUSTOM_BASKET_API_URL=$BASE_URL" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          build-args: |
            VITE_CUSTOM_BASKET_API_URL=${{ env.VITE_CUSTOM_BASKET_API_URL }}
