name: Sonar Quality Gate

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    environment: prd
    env:
      NODE_VERSION: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Verify Sonar configuration
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then echo "::error::Missing SONAR_TOKEN secret. Configure it in the repository settings." && exit 1; fi
          if [ -z "${{ vars.SONAR_ORGANIZATION }}" ]; then echo "::error::Missing SONAR_ORGANIZATION repository variable." && exit 1; fi
          if [ -z "${{ vars.SONAR_PROJECT_KEY }}" ]; then echo "::error::Missing SONAR_PROJECT_KEY repository variable." && exit 1; fi

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm run test:coverage
        env:
          CI: true

      - name: Build project
        run: npm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ba3875ecf642b2129de2b589510c81a8b53dbf4e # master (2025-08-27)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >-
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

# Staging environment: https://staging.d3iwsh8gt9f3of.amplifyapp.com
