name: Sonar Quality Gate

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    environment: prd
    env:
      NODE_VERSION: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify Sonar configuration
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "::error::Missing SONAR_TOKEN secret. Configure it in the repository settings." && exit 1
          fi
          if [ -z "${{ vars.SONAR_ORGANIZATION }}" ]; then
            echo "::error::Missing SONAR_ORGANIZATION repository variable." && exit 1
          fi
          if [ -z "${{ vars.SONAR_PROJECT_KEY }}" ]; then
            echo "::error::Missing SONAR_PROJECT_KEY repository variable." && exit 1
          fi

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm run test:coverage
        env:
          CI: true

      - name: Build project
        run: npm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >-
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
